# Generated by Django 4.2.10 on 2024-02-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(null=True),
        ),
    ]
